# Generated by Django 5.2.6 on 2025-10-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_candidate_email_alter_spot_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
