# Generated by Django 6.0.1 on 2026-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_spot_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='source_channel',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='spot',
            name='last_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='submission_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='source_channel',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='submission',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
