# Generated by Django 6.0.1 on 2026-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spots_contributed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
