# Generated by Django 6.0.1 on 2026-03-12 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0008_candidate_source_channel_spot_last_confirmed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('state', models.CharField(choices=[('awaiting_spot', 'Awaiting spot name/location'), ('awaiting_location', 'Awaiting location details'), ('awaiting_extras', 'Awaiting optional details'), ('complete', 'Submission complete')], default='awaiting_spot', max_length=30)),
                ('partial_data', models.JSONField(blank=True, default=dict)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_sessions', to='places.submission')),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number', '-created_at'], name='whatsapp_wh_phone_n_581390_idx')],
            },
        ),
    ]
